Removing unused files wc68.ko and wlc98_driver.ko
ERROR: wc68.ko has a version of 10291364, expecting 10344740.
ERROR: wlc98_driver.ko has a version of 10291364, expecting 10344740.

Bug: 285813408
Test: build
Change-Id: Icaed873b99e6d44a279f91903d02cb705f80b881